### ISSUE TITLE
different folder output than bundle

### ISSUE THREAD

**Issue by wighawag** [mentaljam/rollup-plugin-favicons#2]
How to write the favicon in a different folder (the root folder) than the bundle (that is in a subfolder)

I have the following rollup config 

```
output: {
    sourcemap: true,
    format: 'iife',
    name: 'app',
    file: 'public/build/bundle.js',
  },
```

And when I use rollup-plugin-favicons it generated them in the `build` folder.
Any options to make it write in `public` folder instead ?

**Comment by mentaljam** [comment]
Hi,
The plugin emits generated files with the [emitFile](https://rollupjs.org/guide/en/#thisemitfileemittedfile-emittedchunk--emittedasset--string) hook. You can adjust output names with the [output.assetFileNames](https://rollupjs.org/guide/en/#outputassetfilenames) option.

**Comment by wighawag** [comment]
Thanks for the answer. I tried output.assetFileNames but it does not work. Also according to rollup doc, the default would be `"assets/[name]-[hash][extname]"` which is not where the icons are generated in. They get generated in `public/build` even though the only reference to it is in `file: 'public/build/bundle.js',`

**Comment by Klowner** [comment]
I'm attempting to do something similar. Can't seem to figure out how to get the favicons to drop into a subdirectory rather than the output root. Works beautifully aside from that!

**Comment by mentaljam** [comment]
Can you, please, test the `rollup-plugin-favicons@beta` version? I fixed emitting favicons, so now you can configure the path with the `assetFileNames` option. I hope it solves your issue.

**Comment by Steakeye** [comment]
> Can you, please, test the `rollup-plugin-favicons@beta` version? I fixed emitting favicons, so now you can configure the path with the `assetFileNames` option. I hope it solves your issue.

I've just tried this, and it doesn't fix my issue, I'm not sure if it fixes the issues @Klowner or @wighawag were having. What I can confirm is that essentially if you create a pattern for asset files and assign that as the `assetFileNames` of the `output` rollup config object, then the assets are able to be put in subfolder should they be defined as part of the pattern (this is standard behavior that rollup controls); the only thing this latest change does is override the favicon plugin `configuration.path` property so that it matches the directories substring of the `assetFileNames` pattern, saving the user from manually setting the `path` property to a matching folder path. This fix doesn't really add new functionality as I'm concerned.

What I'm looking for (and I think @wighawag was asking for this) is a way to write the output files do a location external to the bundle root, somewhere arbitrary in the project root:
```
.
├── dist
|       └── <not here>
└── public
        └<here>
```

In the above example, `dist` is where rollup is outputting everything bundled, but I am serving public assets from a separate public folder. For context, I'm using Sapper/Svelte, and I don't have complete control over where Sapper bundles the application code.

I think the issue doesn't originate with this plugin but is in fact the result of Rollup v2 compared to v1 and a stricter limitation of where processed files are output; they are all expected to bundled under the same directory.

What I need is a workaround, effectively a non FP side-effect, so I can write out the filed to another location. I'm going to for this project and get it working for myself. I'll create a PR for you to see afterwards, in case you want to include it in this plugin.

**Comment by Steakeye** [comment]
PR Created

**Comment by mentaljam** [comment]
Thanks to @Steakeye there a new configuration option `callback` which you can use to provide a custom logic of processing generated assets. Please, see the [example](https://github.com/mentaljam/rollup-plugin-favicons/blob/173c3c92e831f2e15239590b677fafb184c35f4c/example/rollup.config.custom-dir.js) of Rollup configuration. Also please try a newly published `rollup-plugin-favicons@beta` version.
